# Z score

1.It is used to transform the Non StanDARDIZED dATA dISTRIBUTION INTO stndard normal distribution.

2.What is standard normal distt - where mean =0, sd =1

3.Z score = (x-mean)/s.d.

4.The python library scipy.stats

5.The python library is scipy.stats for Z score but for machine learnin we use sklearn.preprocessing :: StandardScaler 

In [1]:
#import the libraries
import numpy as np
import pandas as pd
from scipy.stats import zscore

In [2]:
train = pd.read_csv("C://Users//Astha//Downloads//train.csv") 
meal = pd.read_csv("C://Users//Astha//Downloads//meal.csv")
Humidity = pd.read_csv("C://Users//Astha//Downloads//Humidity.csv")
Weather = pd.read_csv("C://Users//Astha//Downloads//Weather.csv")

#importing csv file from desktop to python terminal
#we will replace the forward slashes by double backward slashes and at the end put the file name after double backward slash

In [3]:
#Apply Z score
zscore(Humidity.temperature)

array([-1.55917378, -1.39408479, -1.06390682,  0.0917161 ,  0.58698307,
        1.24733903,  0.91716105,  0.42189408,  0.75207206])

In [4]:
#Add these Z scored values in 
Humidity["zscore_temp"] = zscore(Humidity.temperature) # adding new column to the Humidity table

In [5]:
Humidity.head()

date      city  temperature  humidity  zscore_temp
0  05/01/17  new york           65        56    -1.559174
1  05/02/17  new york           66        58    -1.394085
2  05/03/17  new york           68        60    -1.063907
3  05/01/17    mumbai           75        80     0.091716
4  05/02/17    mumbai           78        83     0.586983

In [6]:
#the zscore has convert the mean and std to 0 and 1 respectively in order to make it normal standard curve
print(round(Humidity.zscore_temp.mean()))
print(round(Humidity.zscore_temp.std()))

0
1


In [7]:
np.corrcoef(Humidity.temperature,Humidity.humidity)


array([[ 1.        , -0.03662597],
       [-0.03662597,  1.        ]])

In [ ]:
#drop temp
#Humidity = Humidity.drop("temperature",axis =1)

In [8]:
Humidity["zscore_humid"]=zscore(Humidity.humidity)
Humidity

date      city  temperature  humidity  zscore_temp  zscore_humid
0  05/01/17  new york           65        56    -1.559174     -0.046435
1  05/02/17  new york           66        58    -1.394085      0.046435
2  05/03/17  new york           68        60    -1.063907      0.139305
3  05/01/17    mumbai           75        80     0.091716      1.068004
4  05/02/17    mumbai           78        83     0.586983      1.207309
5  05/03/17    mumbai           82        85     1.247339      1.300179
6  05/01/17   beijing           80        26     0.917161     -1.439484
7  05/02/17   beijing           77        30     0.421894     -1.253744
8  05/03/17   beijing           79        35     0.752072     -1.021569

In [9]:
np.corrcoef(Humidity.zscore_humid,Humidity.zscore_temp)

array([[ 1.        , -0.03662597],
       [-0.03662597,  1.        ]])

In [10]:
Humid= Humidity.drop(["humidity","temperature"], axis=1)
Humid

date      city  zscore_temp  zscore_humid
0  05/01/17  new york    -1.559174     -0.046435
1  05/02/17  new york    -1.394085      0.046435
2  05/03/17  new york    -1.063907      0.139305
3  05/01/17    mumbai     0.091716      1.068004
4  05/02/17    mumbai     0.586983      1.207309
5  05/03/17    mumbai     1.247339      1.300179
6  05/01/17   beijing     0.917161     -1.439484
7  05/02/17   beijing     0.421894     -1.253744
8  05/03/17   beijing     0.752072     -1.021569

# When to use axis = 1

Axis = 1,used when we want to drop columns for instance in general.However , in calculqating mean . meadian or sd , axis = 1 means row



# Covariance

1. Covariance is nothing but measure of how fit is correlation. it is measure of correlation.

2.The value of correlation lies between -1 and 1 whereas the value of covariance lies between -infinity to + infinity


In [11]:
Humid.cov() #this means that temp and humid variables not go well with each other 

#cov() covariance function

zscore_temp  zscore_humid
zscore_temp      1.125000     -0.041204
zscore_humid    -0.041204      1.125000

In [12]:
train.cov()

id          week     center_id  \
id                     2.083831e+10  13338.481045  17529.997840   
week                   1.333848e+04   1724.322002     -6.586155   
center_id              1.753000e+04     -6.586155   2113.704856   
meal_id                3.859806e+04    450.413632    248.985790   
checkout_price         4.285730e+04    168.813897      9.476541   
base_price             6.749944e+04    190.959362      4.465995   
emailer_for_promotion  7.887807e+01     -0.009539      0.171468   
homepage_featured      1.400560e+02     -0.107017     -0.072309   
num_orders             4.012503e+04   -282.942655   -965.367349   

                             meal_id  checkout_price    base_price  \
id                      38598.064638    42857.295215  67499.441640   
week                      450.413632      168.813897    190.959362   
center_id                 248.985790        9.476541      4.465995   
meal_id                299669.663796      899.834716    229.198248   
checkout_price            899.834716    23390.558965  23434.157890   
base_price                229.198248    23434.157890  25829.605010   
emailer_for_promotion       2.003365        0.201202      7.512182   
homepage_featured           2.792280       -2.727721      2.865004   
num_orders               2296.681858   -17082.316071 -14145.582841   

                       emailer_for_promotion  homepage_featured     num_orders  
id                                 78.878070         140.055974   40125.025830  
week                               -0.009539          -0.107017    -282.942655  
center_id                           0.171468          -0.072309    -965.367349  
meal_id                             2.003365           2.792280    2296.681858  
checkout_price                      0.201202          -2.727721  -17082.316071  
base_price                          7.512182           2.865004  -14145.582841  
emailer_for_promotion               0.074567           0.033261      29.963571  
homepage_featured                   0.033261           0.097276      36.364962  
num_orders                         29.963571          36.364962  156754.861772

# Map

1. it tries to link the data basis some col values

2. Syntax - map(function_obj,variable)

In [13]:
#Taking city as reference map season in the in the humidity dataset
Season ={"new york":"Winter","mumbai":"Rainy","beijing" : "Spring"}
Season
#the keyvalues should be exactly same as column on whose basis we are goin to map as it will not map the city name if we change case or name it will not able to find it in the table

{'new york': 'Winter', 'mumbai': 'Rainy', 'beijing': 'Spring'}

In [14]:
#Map(link) the season column in the humidity data taking city as reference
Humid["Season"]=Humid["city"].map(Season)
Humid


date      city  zscore_temp  zscore_humid  Season
0  05/01/17  new york    -1.559174     -0.046435  Winter
1  05/02/17  new york    -1.394085      0.046435  Winter
2  05/03/17  new york    -1.063907      0.139305  Winter
3  05/01/17    mumbai     0.091716      1.068004   Rainy
4  05/02/17    mumbai     0.586983      1.207309   Rainy
5  05/03/17    mumbai     1.247339      1.300179   Rainy
6  05/01/17   beijing     0.917161     -1.439484  Spring
7  05/02/17   beijing     0.421894     -1.253744  Spring
8  05/03/17   beijing     0.752072     -1.021569  Spring

In [15]:
#traffic keyvalue pair - Dictionary
Traffic = {"new york": "High traffic","beijing" : "low traffic", "mumbai":"Disastrous traffic"}

In [16]:
#map the traffic according to city
Humid["Traffic"]=Humid["city"].map(Traffic)
Humid

date      city  zscore_temp  zscore_humid  Season             Traffic
0  05/01/17  new york    -1.559174     -0.046435  Winter        High traffic
1  05/02/17  new york    -1.394085      0.046435  Winter        High traffic
2  05/03/17  new york    -1.063907      0.139305  Winter        High traffic
3  05/01/17    mumbai     0.091716      1.068004   Rainy  Disastrous traffic
4  05/02/17    mumbai     0.586983      1.207309   Rainy  Disastrous traffic
5  05/03/17    mumbai     1.247339      1.300179   Rainy  Disastrous traffic
6  05/01/17   beijing     0.917161     -1.439484  Spring         low traffic
7  05/02/17   beijing     0.421894     -1.253744  Spring         low traffic
8  05/03/17   beijing     0.752072     -1.021569  Spring         low traffic

In [17]:
#Another example to understand MAPPING
def sq(x):
    return x**2




In [18]:
#
list(map(lambda x : x ** 2 , Humid.zscore_humid))

[0.002156205079060853,
 0.002156205079060853,
 0.01940584571154768,
 1.1406324868231912,
 1.4575946334451368,
 1.6904647819837089,
 2.07211308097748,
 1.5718735026353616,
 1.043603258265453]

In [19]:
list(map(sq , Humid.zscore_humid))

[0.002156205079060853,
 0.002156205079060853,
 0.01940584571154768,
 1.1406324868231912,
 1.4575946334451368,
 1.6904647819837089,
 2.07211308097748,
 1.5718735026353616,
 1.043603258265453]

In [20]:
Humid["square"]= list(map(sq , Humid.zscore_humid))  #this is how we add a new column to the table Table["newcolumn"] = data
Humid

date      city  zscore_temp  zscore_humid  Season             Traffic  \
0  05/01/17  new york    -1.559174     -0.046435  Winter        High traffic   
1  05/02/17  new york    -1.394085      0.046435  Winter        High traffic   
2  05/03/17  new york    -1.063907      0.139305  Winter        High traffic   
3  05/01/17    mumbai     0.091716      1.068004   Rainy  Disastrous traffic   
4  05/02/17    mumbai     0.586983      1.207309   Rainy  Disastrous traffic   
5  05/03/17    mumbai     1.247339      1.300179   Rainy  Disastrous traffic   
6  05/01/17   beijing     0.917161     -1.439484  Spring         low traffic   
7  05/02/17   beijing     0.421894     -1.253744  Spring         low traffic   
8  05/03/17   beijing     0.752072     -1.021569  Spring         low traffic   

     square  
0  0.002156  
1  0.002156  
2  0.019406  
3  1.140632  
4  1.457595  
5  1.690465  
6  2.072113  
7  1.571874  
8  1.043603

# Incase of merge, it is compatible with the data frame functions for eg we saw the newtrain dataset that emerged from merge() but with map,in order to link , i need to have the linked data in form of dictionary and hence merge appears more flexible and faster in comparison to map

In [32]:
#replacing mumbai and beijing with new delhi and SF
Humid.replace(to_replace=["mumbai","beijing"] ,value=["new delhi","SF"])

date       city  zscore_temp  zscore_humid  Season             Traffic  \
0  05/01/17   new york    -1.559174     -0.046435  Winter        High traffic   
1  05/02/17   new york    -1.394085      0.046435  Winter        High traffic   
2  05/03/17   new york    -1.063907      0.139305  Winter        High traffic   
3  05/01/17  new delhi     0.091716      1.068004   Rainy  Disastrous traffic   
4  05/02/17  new delhi     0.586983      1.207309   Rainy  Disastrous traffic   
5  05/03/17  new delhi     1.247339      1.300179   Rainy  Disastrous traffic   
6  05/01/17         SF     0.917161     -1.439484  Spring         low traffic   
7  05/02/17         SF     0.421894     -1.253744  Spring         low traffic   
8  05/03/17         SF     0.752072     -1.021569  Spring         low traffic   

     square  
0  0.002156  
1  0.002156  
2  0.019406  
3  1.140632  
4  1.457595  
5  1.690465  
6  2.072113  
7  1.571874  
8  1.043603

In [21]:
#rename a column
Humid.rename(columns={"city":"City"})

date      City  zscore_temp  zscore_humid  Season             Traffic  \
0  05/01/17  new york    -1.559174     -0.046435  Winter        High traffic   
1  05/02/17  new york    -1.394085      0.046435  Winter        High traffic   
2  05/03/17  new york    -1.063907      0.139305  Winter        High traffic   
3  05/01/17    mumbai     0.091716      1.068004   Rainy  Disastrous traffic   
4  05/02/17    mumbai     0.586983      1.207309   Rainy  Disastrous traffic   
5  05/03/17    mumbai     1.247339      1.300179   Rainy  Disastrous traffic   
6  05/01/17   beijing     0.917161     -1.439484  Spring         low traffic   
7  05/02/17   beijing     0.421894     -1.253744  Spring         low traffic   
8  05/03/17   beijing     0.752072     -1.021569  Spring         low traffic   

     square  
0  0.002156  
1  0.002156  
2  0.019406  
3  1.140632  
4  1.457595  
5  1.690465  
6  2.072113  
7  1.571874  
8  1.043603

In [22]:
def find_new(title):
    if "new" in title.lower():
        return True
    else:
        return False
    
sum(Humid.city.apply(lambda x : find_new(x)))

#apply function uses lambda fuction

3

In [ ]:
plt.plot(range(1,10),wcss,"o-",markerfacecolor="red",linestyle="dashed" , markersize=10)
plt.xlabel("K cluster values")
plt.ylabel("WCSS values")
plt.title("Elbow plot")

In [ ]:
plt.scatter(x="sepal length (cm)" , y="sepal width (cm)" , data = iris , c=labels , s = 20 )
plt.scatter(x= centroid[:,0],y = centroid[:,1] , data = iris , marker="d" , color="blue", s=80)
plt.xlabel("sepal length")
plt.ylabel("sepal width")
plt.title("Clustering using sepal length- sepal width")

In [ ]:
plt.scatter(newmall[newmall.Labels==0]["Annual Income (k$)"], 
           newmall[newmall.Labels==0]["Spending Score (1-100)"] , label = "Sensitive")

plt.scatter(newmall[newmall.Labels==1]["Annual Income (k$)"], 
           newmall[newmall.Labels==1]["Spending Score (1-100)"] , label = "Standard")

plt.scatter(newmall[newmall.Labels==2]["Annual Income (k$)"], 
           newmall[newmall.Labels==2]["Spending Score (1-100)"] , label = "Target")

plt.scatter(newmall[newmall.Labels==3]["Annual Income (k$)"], 
           newmall[newmall.Labels==3]["Spending Score (1-100)"] , label = "Careless")

plt.scatter(newmall[newmall.Labels==4]["Annual Income (k$)"], 
           newmall[newmall.Labels==4]["Spending Score (1-100)"] , label = "Careful")

plt.legend()
plt.xlabel("Annual Income")
plt.ylabel("Spending Score")
plt.title("Hierarchial Clustering")

In [ ]:
#lmplot bw grad rate and room board
sns.lmplot(x="Grad.Rate" , y="Room.Board" , data=college , hue="Private")

In [ ]:
sex_surv_table = pd.crosstab(index=train["Survived"], 
                          columns=train["Sex"])
sex_surv_table 

In [ ]:
sex_surv_table.plot(kind="bar", 
                 figsize=(2,2),
                 stacked=True)

In [ ]:

#a=train["Name"].str.split(',',2, expand=True)
#a
#b=a[1].str.split(".",0,expand=True)
#b
#train["Title"]=b[0]
#train.head()
train["Title"].value_counts()
#train=train.drop("Title" , axis=1)